<?php
/**
 * Studioforty9_Recaptcha
 *
 * @category  Studioforty9
 * @package   Studioforty9_Recaptcha
 * @author    StudioForty9 <info@studioforty9.com>
 * @copyright 2014 StudioForty9 (http://www.studioforty9.com)
 * @license   https://github.com/studioforty9/recaptcha/blob/master/LICENCE MIT
 * @version   1.0.0
 * @link      https://github.com/studioforty9/recaptcha
 */
?>
<div class="recaptcha">
    <?php echo $this->getRecaptchaHtml(); ?>
    <?php echo $this->getRecaptchaScript(); ?>
</div>
