<?php
/**
 * Studioforty9_Recaptcha
 *
 * @category  Studioforty9
 * @package   Studioforty9_Recaptcha
 * @author    StudioForty9 <info@studioforty9.com>
 * @copyright 2015 StudioForty9 (http://www.studioforty9.com)
 * @license   https://github.com/studioforty9/recaptcha/blob/master/LICENCE BSD
 * @version   1.1.0
 * @link      https://github.com/studioforty9/recaptcha
 * @see       Studioforty9_Recaptcha_Block_Autorender
 */
?>
<?php if ($this->isAllowed($this->getRequest()->getRouteName())): ?>
<div class="recaptcha">
    <?php echo $this->getRecaptchaHtml(); ?>
    <?php echo $this->getRecaptchaScript(); ?>

</div>
<?php endif; ?>
