<?php
/**
 * Studioforty9_Recaptcha
 *
 * @category  Studioforty9
 * @package   Studioforty9_Recaptcha
 * @author    StudioForty9 <info@studioforty9.com>
 * @copyright 2014 StudioForty9 (http://www.studioforty9.com)
 * @license   https://github.com/studioforty9/recaptcha/blob/master/LICENCE BSD
 * @version   1.0.0
 * @link      https://github.com/studioforty9/recaptcha
 * @see       Studioforty9_Recaptcha_Block_Explicit
 */
?>
<div class="recaptcha">
    <input type="checkbox" id="recaptcha-verification-1" name="recaptcha-verification-1" value="" class="hide required-entry" />
    <div id="recaptcha-1"></div>
    <script type="text/javascript">
        var onloadCallback = function() {
            grecaptcha.render('recaptcha-1', {
                'sitekey': "<?php echo $this->getSiteKey(); ?>",
                'theme': "<?php echo $this->getTheme(); ?>",
                'callback': function(response) {
                    if (response.length === 420) {
                        $('recaptcha-verification-1').writeAttribute('value', 'checked');
                        $('recaptcha-verification-1').checked = true;
                    } else {
                        $('recaptcha-verification-1').writeAttribute('value', '');
                        $('recaptcha-verification-1').checked = false;
                    }
                }
            });
        };
    </script>
    <?php echo $this->getRecaptchaScript(); ?>
</div>
